### ISSUE TITLE
"Unhandled rejection TypeError:....." in hexo server 

### ISSUE THREAD

**Issue by AplexOS** [ppoffice/hexo-theme-hueman#121]
```
Unhandled rejection TypeError: /home/zengjf/os/AplexOS.github.io/themes/hexo-theme-hueman/layout/index.ejs:1
 >> 1| <%- partial('common/archive') %>

/home/zengjf/os/AplexOS.github.io/themes/hexo-theme-hueman/layout/common/archive.ejs:19
    17|         <div class="article-row">
    18|     <% } %>
 >> 19|         <%- partial('summary', { post: post }) %>
    20|     <% if (postCount == page.posts.length || postCount % 2 == 0) { %>
    21|         </div>
    22|     <% } %>

/home/zengjf/os/AplexOS.github.io/themes/hexo-theme-hueman/layout/common/summary.ejs:3
    1| <article class="article article-summary">
    2|     <div class="article-summary-inner">
 >> 3|         <% if (theme.customize.thumbnail === true) { %>
    4|         <%- partial('common/thumbnail', { counter: true }) %>
    5|         <% } %>
    6|         <div class="article-meta">

Cannot read property 'thumbnail' of undefined
    at eval (eval at <anonymous> (/home/zengjf/os/AplexOS.github.io/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:144)
    at eval (eval at <anonymous> (/home/zengjf/os/AplexOS.github.io/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:36:492)
    at /home/zengjf/os/AplexOS.github.io/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:255:15
    at Object.exports.render (/home/zengjf/os/AplexOS.github.io/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:293:13)
    at Hexo.ejsRenderer (/home/zengjf/os/AplexOS.github.io/node_modules/hexo-renderer-ejs/lib/renderer.js:7:14)
    at Render.renderSync (/home/zengjf/os/AplexOS.github.io/node_modules/hexo/lib/hexo/render.js:95:23)
    at _compiledSync (/home/zengjf/os/AplexOS.github.io/node_modules/hexo/lib/theme/view.js:109:21)
    at View.renderSync (/home/zengjf/os/AplexOS.github.io/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/zengjf/os/AplexOS.github.io/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/home/zengjf/os/AplexOS.github.io/node_modules/hexo/node_modules/lodash/lodash.js:4436:19)
    at eval (eval at <anonymous> (/home/zengjf/os/AplexOS.github.io/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:1078)
    at Query.forEach (/home/zengjf/os/AplexOS.github.io/node_modules/hexo/node_modules/warehouse/lib/query.js:42:5)
    at eval (eval at <anonymous> (/home/zengjf/os/AplexOS.github.io/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:104)
    at eval (eval at <anonymous> (/home/zengjf/os/AplexOS.github.io/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:1849)
    at /home/zengjf/os/AplexOS.github.io/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:255:15
    at Object.exports.render (/home/zengjf/os/AplexOS.github.io/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:293:13)
    at Hexo.ejsRenderer (/home/zengjf/os/AplexOS.github.io/node_modules/hexo-renderer-ejs/lib/renderer.js:7:14)
    at Render.renderSync (/home/zengjf/os/AplexOS.github.io/node_modules/hexo/lib/hexo/render.js:95:23)
    at _compiledSync (/home/zengjf/os/AplexOS.github.io/node_modules/hexo/lib/theme/view.js:109:21)
    at View.renderSync (/home/zengjf/os/AplexOS.github.io/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/zengjf/os/AplexOS.github.io/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/home/zengjf/os/AplexOS.github.io/node_modules/hexo/node_modules/lodash/lodash.js:4436:19)
    at eval (eval at <anonymous> (/home/zengjf/os/AplexOS.github.io/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:35)
    at eval (eval at <anonymous> (/home/zengjf/os/AplexOS.github.io/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:71)
    at /home/zengjf/os/AplexOS.github.io/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:255:15
    at Object.exports.render (/home/zengjf/os/AplexOS.github.io/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:293:13)
    at Hexo.ejsRenderer (/home/zengjf/os/AplexOS.github.io/node_modules/hexo-renderer-ejs/lib/renderer.js:7:14)
    at Hexo.tryCatcher (/home/zengjf/os/AplexOS.github.io/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/home/zengjf/os/AplexOS.github.io/node_modules/hexo/node_modules/bluebird/js/release/method.js:15:34)
    at /home/zengjf/os/AplexOS.github.io/node_modules/hexo/lib/hexo/render.js:59:21
    at tryCatcher (/home/zengjf/os/AplexOS.github.io/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/zengjf/os/AplexOS.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/home/zengjf/os/AplexOS.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromiseCtx (/home/zengjf/os/AplexOS.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:596:10)
```

**Comment by ppoffice** [comment]
Did you rename `_config.yml.example` to `_config.yml` as [Wiki/Installation](https://github.com/ppoffice/hexo-theme-hueman/wiki/Installation) describes?

**Comment by AplexOS** [comment]
@ppoffice 
Thank you for reminding , now works well.

**Comment by carlospliego** [comment]
I also experienced this after the first step where it says
`cd themes/hueman'

I forgot to cd back to the parent directory.
