### ISSUE TITLE
hexo-generator-json-content加载失败

### ISSUE THREAD

**Issue by buweilv** [ppoffice/hexo-theme-hueman#155]
按照配置配置好，并且利用指令cnpm install -S hexo-generator-json-content安装插件。
pakage.json内容如下：
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.2.2"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-deployer-git": "^0.2.0",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-json-content": "^3.0.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.2.0",
    "hexo-renderer-marked": "^0.2.10",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0"
  }
}
```
hexo s执行后出现如下错误：
```
ERROR Plugin load failed: hexo-generator-json-content
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at Object.exports.runInThisContext (vm.js:53:16)
    at /home/buwei/blog/node_modules/hexo/lib/hexo/index.js:227:17
    at tryCatcher (/home/buwei/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/buwei/blog/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/buwei/blog/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/buwei/blog/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/buwei/blog/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/home/buwei/blog/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/home/buwei/blog/node_modules/bluebird/js/release/promise.js:431:57)
    at Promise._settlePromiseFromHandler (/home/buwei/blog/node_modules/bluebird/js/release/promise.js:522:17)
    at Promise._settlePromise (/home/buwei/blog/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/buwei/blog/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/buwei/blog/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/home/buwei/blog/node_modules/bluebird/js/release/promise.js:636:18)
    at /home/buwei/blog/node_modules/bluebird/js/release/nodeback.js:42:21
    at /home/buwei/blog/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
```

**Comment by ppoffice** [comment]
@buweilv 是不是Node的版本太低了？

**Comment by ppoffice** [comment]
@buweilv 是不是Node的版本太低了？

**Comment by buweilv** [comment]
@ppoffice 确实是node版本低，用的ubuntu16.04以为自带的是最新版本的node，ubuntu16.04的用户可以注意，自带的node版本太低，可以使用http://askubuntu.com/questions/786272/why-does-installing-node-6-x-on-ubuntu-16-04-actually-install-node-4-2-6升级node。升级之后问题解决。

**Comment by 1900zyh** [comment]
updating node is no use in my case.
I use `npm install hexo-generator-json-content@1 --save` to solve my problem.
And now, it dose work.
