### ISSUE TITLE
Unhandled rejection TypeError: /home/jack/Projects/myblock/block/themes/hexo-theme-hueman/layout/post.ejs:1

### ISSUE THREAD

**Issue by zhcroman** [ppoffice/hexo-theme-hueman#171]
Please make sure these boxes are checked before submitting your issue. Thank you!

- [ ] I have setuped and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [ ] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-hueman/wiki) carefully and created my own configuration file(_config.yml);
- [ ] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-hueman/issues) and found no duplicate issues.

请在发布新Issue之前确保你已经进行了如下工作，谢谢！

- [x] 我已经按照[Hexo官方文档](https://hexo.io/)中的步骤安装与配置了Hexo；
- [x] 我已经仔细地阅读了[主题Wiki](https://github.com/ppoffice/hexo-theme-hueman/wiki)并创建了自己的配置文件(_config.yml)；
- [x] 我已经搜索了[Issues](https://github.com/ppoffice/hexo-theme-hueman/issues)，并且没有找到类似的问题。

**Comment by zhcroman** [comment]
nhandled rejection TypeError: /home/jack/Projects/myblock/block/themes/hexo-theme-hueman/layout/post.ejs:1
 >> 1| <%- partial('common/article', { post: page }) %>

/home/jack/Projects/myblock/block/themes/hexo-theme-hueman/layout/common/article.ejs:23
    21|     </div>
    22| </article>
 >> 23| <%- partial('comment/index') %>

/home/jack/Projects/myblock/block/themes/hexo-theme-hueman/layout/comment/index.ejs:3
    1| <% if (post.comments) { %>
    2|     <section id="comments">
 >> 3|     <% if (theme.comment.disqus) { %>
    4|         <%- partial('comment/disqus') %>
    5|     <% } else if (theme.comment.duoshuo) { %>
    6|         <%- partial('comment/duoshuo') %>

Cannot read property 'disqus' of undefined
    at eval (eval at <anonymous> (/home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:139)
    at eval (eval at <anonymous> (/home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:880)
    at /home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:255:15
    at _compiledSync (/home/jack/Projects/myblock/block/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/home/jack/Projects/myblock/block/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/jack/Projects/myblock/block/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/home/jack/Projects/myblock/block/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at <anonymous> (/home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:1416)
    at eval (eval at <anonymous> (/home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:1451)
    at /home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:255:15
    at _compiledSync (/home/jack/Projects/myblock/block/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/home/jack/Projects/myblock/block/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/jack/Projects/myblock/block/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/home/jack/Projects/myblock/block/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at <anonymous> (/home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:35)
    at eval (eval at <anonymous> (/home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:87)
    at /home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/home/jack/Projects/myblock/block/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/home/jack/Projects/myblock/block/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/jack/Projects/myblock/block/node_modules/hexo/lib/hexo/index.js:388:25
    at tryCatcher (/home/jack/Projects/myblock/block/node_modules/bluebird/js/release/util.js:16:23)
    at /home/jack/Projects/myblock/block/node_modules/bluebird/js/release/method.js:15:34

Unhandled rejection TypeError: /home/jack/Projects/myblock/block/themes/hexo-theme-hueman/layout/archive.ejs:1
 >> 1| <%- partial('common/archive') %>

/home/jack/Projects/myblock/block/themes/hexo-theme-hueman/layout/common/archive.ejs:19
    17|         <div class="article-row">
    18|     <% } %>
 >> 19|         <%- partial('summary', { post: post }) %>
    20|     <% if (postCount == page.posts.length || postCount % 2 == 0) { %>
    21|         </div>
    22|     <% } %>

/home/jack/Projects/myblock/block/themes/hexo-theme-hueman/layout/common/summary.ejs:3
    1| <article class="article article-summary<%= (post.direction && post.direction.toLowerCase() === 'rtl' ? ' rtl' : '') %>">
    2|     <div class="article-summary-inner">
 >> 3|         <% if (theme.customize.thumbnail === true) { %>
    4|         <%- partial('common/thumbnail', { counter: true }) %>
    5|         <% } %>
    6|         <div class="article-meta">

Cannot read property 'thumbnail' of undefined
    at eval (eval at <anonymous> (/home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:252)
    at eval (eval at <anonymous> (/home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:36:498)
    at /home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:255:15
    at _compiledSync (/home/jack/Projects/myblock/block/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/home/jack/Projects/myblock/block/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/jack/Projects/myblock/block/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/home/jack/Projects/myblock/block/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at <anonymous> (/home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:1078)
    at Query.forEach (/home/jack/Projects/myblock/block/node_modules/warehouse/lib/query.js:42:5)
    at eval (eval at <anonymous> (/home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:104)
    at eval (eval at <anonymous> (/home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:1849)
    at /home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:255:15
    at _compiledSync (/home/jack/Projects/myblock/block/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/home/jack/Projects/myblock/block/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/jack/Projects/myblock/block/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/home/jack/Projects/myblock/block/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at <anonymous> (/home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:35)
    at eval (eval at <anonymous> (/home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:71)
    at /home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/home/jack/Projects/myblock/block/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/home/jack/Projects/myblock/block/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/jack/Projects/myblock/block/node_modules/hexo/lib/hexo/index.js:388:25

Unhandled rejection TypeError: /home/jack/Projects/myblock/block/themes/hexo-theme-hueman/layout/archive.ejs:1
 >> 1| <%- partial('common/archive') %>

/home/jack/Projects/myblock/block/themes/hexo-theme-hueman/layout/common/archive.ejs:19
    17|         <div class="article-row">
    18|     <% } %>
 >> 19|         <%- partial('summary', { post: post }) %>
    20|     <% if (postCount == page.posts.length || postCount % 2 == 0) { %>
    21|         </div>
    22|     <% } %>

/home/jack/Projects/myblock/block/themes/hexo-theme-hueman/layout/common/summary.ejs:3
    1| <article class="article article-summary<%= (post.direction && post.direction.toLowerCase() === 'rtl' ? ' rtl' : '') %>">
    2|     <div class="article-summary-inner">
 >> 3|         <% if (theme.customize.thumbnail === true) { %>
    4|         <%- partial('common/thumbnail', { counter: true }) %>
    5|         <% } %>
    6|         <div class="article-meta">

Cannot read property 'thumbnail' of undefined
    at eval (eval at <anonymous> (/home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:252)
    at eval (eval at <anonymous> (/home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:36:498)
    at /home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:255:15
    at _compiledSync (/home/jack/Projects/myblock/block/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/home/jack/Projects/myblock/block/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/jack/Projects/myblock/block/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/home/jack/Projects/myblock/block/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at <anonymous> (/home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:1078)
    at Query.forEach (/home/jack/Projects/myblock/block/node_modules/warehouse/lib/query.js:42:5)
    at eval (eval at <anonymous> (/home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:104)
    at eval (eval at <anonymous> (/home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:1849)
    at /home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:255:15
    at _compiledSync (/home/jack/Projects/myblock/block/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/home/jack/Projects/myblock/block/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/jack/Projects/myblock/block/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/home/jack/Projects/myblock/block/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at <anonymous> (/home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:35)
    at eval (eval at <anonymous> (/home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:71)
    at /home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/home/jack/Projects/myblock/block/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/home/jack/Projects/myblock/block/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/jack/Projects/myblock/block/node_modules/hexo/lib/hexo/index.js:388:25

Unhandled rejection TypeError: /home/jack/Projects/myblock/block/themes/hexo-theme-hueman/layout/archive.ejs:1
 >> 1| <%- partial('common/archive') %>

/home/jack/Projects/myblock/block/themes/hexo-theme-hueman/layout/common/archive.ejs:19
    17|         <div class="article-row">
    18|     <% } %>
 >> 19|         <%- partial('summary', { post: post }) %>
    20|     <% if (postCount == page.posts.length || postCount % 2 == 0) { %>
    21|         </div>
    22|     <% } %>

/home/jack/Projects/myblock/block/themes/hexo-theme-hueman/layout/common/summary.ejs:3
    1| <article class="article article-summary<%= (post.direction && post.direction.toLowerCase() === 'rtl' ? ' rtl' : '') %>">
    2|     <div class="article-summary-inner">
 >> 3|         <% if (theme.customize.thumbnail === true) { %>
    4|         <%- partial('common/thumbnail', { counter: true }) %>
    5|         <% } %>
    6|         <div class="article-meta">

Cannot read property 'thumbnail' of undefined
    at eval (eval at <anonymous> (/home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:252)
    at eval (eval at <anonymous> (/home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:36:498)
    at /home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:255:15
    at _compiledSync (/home/jack/Projects/myblock/block/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/home/jack/Projects/myblock/block/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/jack/Projects/myblock/block/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/home/jack/Projects/myblock/block/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at <anonymous> (/home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:1078)
    at Query.forEach (/home/jack/Projects/myblock/block/node_modules/warehouse/lib/query.js:42:5)
    at eval (eval at <anonymous> (/home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:104)
    at eval (eval at <anonymous> (/home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:1849)
    at /home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:255:15
    at _compiledSync (/home/jack/Projects/myblock/block/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/home/jack/Projects/myblock/block/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/jack/Projects/myblock/block/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/home/jack/Projects/myblock/block/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at <anonymous> (/home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:35)
    at eval (eval at <anonymous> (/home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:71)
    at /home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/home/jack/Projects/myblock/block/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/home/jack/Projects/myblock/block/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/jack/Projects/myblock/block/node_modules/hexo/lib/hexo/index.js:388:25

Unhandled rejection TypeError: /home/jack/Projects/myblock/block/themes/hexo-theme-hueman/layout/index.ejs:1
 >> 1| <%- partial('common/archive') %>

/home/jack/Projects/myblock/block/themes/hexo-theme-hueman/layout/common/archive.ejs:19
    17|         <div class="article-row">
    18|     <% } %>
 >> 19|         <%- partial('summary', { post: post }) %>
    20|     <% if (postCount == page.posts.length || postCount % 2 == 0) { %>
    21|         </div>
    22|     <% } %>

/home/jack/Projects/myblock/block/themes/hexo-theme-hueman/layout/common/summary.ejs:3
    1| <article class="article article-summary<%= (post.direction && post.direction.toLowerCase() === 'rtl' ? ' rtl' : '') %>">
    2|     <div class="article-summary-inner">
 >> 3|         <% if (theme.customize.thumbnail === true) { %>
    4|         <%- partial('common/thumbnail', { counter: true }) %>
    5|         <% } %>
    6|         <div class="article-meta">

Cannot read property 'thumbnail' of undefined
    at eval (eval at <anonymous> (/home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:252)
    at eval (eval at <anonymous> (/home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:36:498)
    at /home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:255:15
    at _compiledSync (/home/jack/Projects/myblock/block/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/home/jack/Projects/myblock/block/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/jack/Projects/myblock/block/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/home/jack/Projects/myblock/block/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at <anonymous> (/home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:1078)
    at Query.forEach (/home/jack/Projects/myblock/block/node_modules/warehouse/lib/query.js:42:5)
    at eval (eval at <anonymous> (/home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:104)
    at eval (eval at <anonymous> (/home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:1849)
    at /home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:255:15
    at _compiledSync (/home/jack/Projects/myblock/block/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/home/jack/Projects/myblock/block/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/jack/Projects/myblock/block/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/home/jack/Projects/myblock/block/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at <anonymous> (/home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:35)
    at eval (eval at <anonymous> (/home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:71)
    at /home/jack/Projects/myblock/block/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/home/jack/Projects/myblock/block/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/home/jack/Projects/myblock/block/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/jack/Projects/myblock/block/node_modules/hexo/lib/hexo/index.js:388:25

ERROR Asset render failed: css/style.css
CoercionError: /home/jack/Projects/myblock/block/themes/hexo-theme-hueman/source/css/_variables.styl:38:54
   34| line-height-title = 1.3em
   35| 
   36| // Header
   37| logo-url = hexo-config("customize.logo.url")
   38| logo-width = 0px + hexo-config("customize.logo.width")
------------------------------------------------------------^
   39| logo-height = 0px + hexo-config("customize.logo.height")
   40| 
   41| // Sidebar

cannot coerce '' to unit

    at Unit.Node.coerce (/home/jack/Projects/myblock/block/node_modules/stylus/lib/nodes/node.js:248:11)
    at Unit.coerce (/home/jack/Projects/myblock/block/node_modules/stylus/lib/nodes/unit.js:209:43)
    at Unit.operate (/home/jack/Projects/myblock/block/node_modules/stylus/lib/nodes/unit.js:132:20)
    at Evaluator.visitBinOp (/home/jack/Projects/myblock/block/node_modules/stylus/lib/visitor/evaluator.js:581:28)
    at Evaluator.Visitor.visit (/home/jack/Projects/myblock/block/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/home/jack/Projects/myblock/block/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at Evaluator.visitExpression (/home/jack/Projects/myblock/block/node_modules/stylus/lib/visitor/evaluator.js:644:26)
    at Evaluator.Visitor.visit (/home/jack/Projects/myblock/block/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/home/jack/Projects/myblock/block/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at Evaluator.visitIdent (/home/jack/Projects/myblock/block/node_modules/stylus/lib/visitor/evaluator.js:551:22)
    at Evaluator.Visitor.visit (/home/jack/Projects/myblock/block/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/home/jack/Projects/myblock/block/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at Evaluator.visitBlock (/home/jack/Projects/myblock/block/node_modules/stylus/lib/visitor/evaluator.js:720:39)
    at Evaluator.Visitor.visit (/home/jack/Projects/myblock/block/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/home/jack/Projects/myblock/block/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at Evaluator.importFile (/home/jack/Projects/myblock/block/node_modules/stylus/lib/visitor/evaluator.js:99:18)
    at Evaluator.visitImport (/home/jack/Projects/myblock/block/node_modules/stylus/lib/visitor/evaluator.js:920:27)
    at Evaluator.Visitor.visit (/home/jack/Projects/myblock/block/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/home/jack/Projects/myblock/block/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at Evaluator.visitRoot (/home/jack/Projects/myblock/block/node_modules/stylus/lib/visitor/evaluator.js:707:27)
    at Evaluator.Visitor.visit (/home/jack/Projects/myblock/block/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/home/jack/Projects/myblock/block/node_modules/stylus/lib/visitor/evaluator.js:160:18)
INFO  Generated: css/images/opacity-10.png
INFO  Generated: js/insight.js
INFO  Generated: css/style.css
INFO  Generated: js/main.js
INFO  Generated: css/images/logo-header.png
INFO  Generated: css/images/s-left.png
INFO  Generated: css/images/thumb-default-small.png
INFO  Generated: css/images/thumb-default.png
INFO  Generated: libs/lightgallery/css/lg-fb-comment-box.css.map
INFO  Generated: libs/source-code-pro/fonts/mrl8jkM18OlOQN8JLgasD9V_2ngZ8dMf8fLgjYEouxg.woff2
INFO  Generated: libs/font-awesome/css/font-awesome.css
INFO  Generated: libs/jquery/2.0.3/jquery.min.js
INFO  Generated: libs/titillium-web/fonts/7XUFZ5tgS-tD6QamInJTcSo_WB_cotcEMUw1LsIE8mM.woff2
INFO  Generated: libs/justified-gallery/justifiedGallery.min.css
INFO  Generated: libs/lightgallery/js/lg-autoplay.js
INFO  Generated: libs/lightgallery/fonts/lg.eot
INFO  Generated: libs/lightgallery/img/loading.gif
INFO  Generated: libs/font-awesome/fonts/fontawesome-webfont.ttf
INFO  Generated: libs/font-awesome/fonts/fontawesome-webfont.svg
INFO  Generated: libs/titillium-web/styles.css
INFO  Generated: libs/source-code-pro/styles.css
INFO  Generated: libs/lightgallery/css/lg-fb-comment-box.css
INFO  Generated: libs/lightgallery/css/lg-fb-comment-box.min.css
INFO  Generated: libs/lightgallery/js/lg-autoplay.min.js
INFO  Generated: libs/lightgallery/js/lg-fullscreen.js
INFO  Generated: libs/lightgallery/js/lg-hash.js
INFO  Generated: libs/lightgallery/js/lg-fullscreen.min.js
INFO  Generated: libs/lightgallery/js/lg-pager.js
INFO  Generated: libs/lightgallery/js/lg-hash.min.js
INFO  Generated: libs/lightgallery/js/lg-pager.min.js
INFO  Generated: libs/lightgallery/js/lg-share.js
INFO  Generated: libs/lightgallery/js/lg-share.min.js
INFO  Generated: libs/lightgallery/js/lg-thumbnail.min.js
INFO  Generated: libs/lightgallery/js/lg-video.min.js
INFO  Generated: libs/lightgallery/js/lg-video.js
INFO  Generated: libs/lightgallery/js/lg-zoom.min.js
INFO  Generated: libs/justified-gallery/jquery.justifiedGallery.min.js
INFO  Generated: libs/font-awesome/css/font-awesome.min.css
INFO  Generated: libs/lightgallery/css/lightgallery.css
INFO  Generated: libs/lightgallery/css/lg-transitions.css
INFO  Generated: libs/lightgallery/css/lightgallery.min.css
INFO  Generated: libs/lightgallery/js/lg-thumbnail.js
INFO  Generated: libs/lightgallery/css/lg-transitions.min.css
INFO  Generated: libs/lightgallery/js/lg-zoom.js
INFO  Generated: libs/lightgallery/js/lightgallery.min.js
INFO  Generated: libs/lightgallery/css/lg-transitions.css.map
INFO  Generated: libs/lightgallery/css/lightgallery.css.map
INFO  Generated: libs/lightgallery/fonts/lg.ttf
INFO  Generated: libs/lightgallery/js/lightgallery.js
INFO  Generated: libs/lightgallery/fonts/lg.svg
INFO  Generated: libs/lightgallery/fonts/lg.woff
INFO  Generated: libs/lightgallery/img/video-play.png
INFO  Generated: libs/lightgallery/img/vimeo-play.png
INFO  Generated: libs/lightgallery/img/youtube-play.png
INFO  Generated: libs/source-code-pro/fonts/mrl8jkM18OlOQN8JLgasDy2Q8seG17bfDXYR_jUsrzg.woff2
INFO  Generated: libs/titillium-web/fonts/7XUFZ5tgS-tD6QamInJTcZSnX671uNZIV63UdXh3Mg0.woff2
INFO  Generated: libs/titillium-web/fonts/anMUvcNT0H1YN4FII8wpr4-67659ICLY8bMrYhtePPA.woff2
INFO  Generated: libs/titillium-web/fonts/anMUvcNT0H1YN4FII8wpr46gJz9aNFrmnwBdd69aqzY.woff2
INFO  Generated: libs/titillium-web/fonts/anMUvcNT0H1YN4FII8wpr9INifKjd1RJ3NxxEi9Cy2w.woff2
INFO  Generated: libs/titillium-web/fonts/anMUvcNT0H1YN4FII8wpr_SNRT0fZ5CX-AqRkMYgJJo.woff2
INFO  Generated: libs/font-awesome/fonts/fontawesome-webfont.eot
INFO  Generated: libs/font-awesome/fonts/fontawesome-webfont.woff
INFO  Generated: libs/font-awesome/fonts/FontAwesome.otf
INFO  Generated: libs/font-awesome/fonts/fontawesome-webfont.woff2

**Comment by ppoffice** [comment]
@zhcroman 
Please check out the [Wiki](https://github.com/ppoffice/hexo-theme-hueman/wiki) to set up your configurations.

**Comment by zhcroman** [comment]
@ppoffice  thanks ,I  know that  i  forget to mv _config.yml.example  _config.yml,now i can use it .
