### ISSUE TITLE
page error

### ISSUE THREAD

**Issue by zhangws0994** [ppoffice/hexo-theme-hueman#212]
/hexo-theme-hueman/layout/index.ejs:1
 >> 1| <%- partial('common/archive') %>

/workspace/blog/themes/hexo-theme-hueman/layout/common/archive.ejs:19
    17|         <div class="article-row">
    18|     <% } %>
 >> 19|         <%- partial('summary', { post: post }) %>
    20|     <% if (postCount == page.posts.length || postCount % 2 == 0) { %>
    21|         </div>
    22|     <% } %>

/workspace/blog/themes/hexo-theme-hueman/layout/common/summary.ejs:3
    1| <article class="article article-summary<%= (post.direction && post.direction.toLowerCase() === 'rtl' ? ' rtl' : '') %>">
    2|     <div class="article-summary-inner">
 >> 3|         <% if (theme.customize.thumbnail === true) { %>
    4|         <%- partial('common/thumbnail', { counter: true }) %>
    5|         <% } %>
    6|         <div class="article-meta">

Cannot read property 'thumbnail' of undefined
    at eval (eval at compile (/workspace/blog/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:13:28)
    at returnedFn (/workspace/blog/node_modules/ejs/lib/ejs.js:580:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (/workspace/blog/node_modules/hexo/lib/theme/view.js:120:22)
    at Theme._View.View.View.renderSync (/workspace/blog/node_modules/hexo/lib/theme/view.js:48:23)
    at Object.partial (/workspace/blog/node_modules/hexo/lib/plugins/helper/partial.js:39:15)
    at Object.wrapper [as partial] (/workspace/blog/node_modules/lodash/lodash.js:4941:19)
    at eval (eval at compile (/workspace/blog/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:47:17)
    at Model._Query.Query.Query.forEach (/workspace/blog/node_modules/warehouse/lib/query.js:42:5)
    at eval (eval at compile (/workspace/blog/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:12:19)
    at returnedFn (/workspace/blog/node_modules/ejs/lib/ejs.js:580:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (/workspace/blog/node_modules/hexo/lib/theme/view.js:120:22)
    at Theme._View.View.View.renderSync (/workspace/blog/node_modules/hexo/lib/theme/view.js:48:23)
    at Object.partial (/workspace/blog/node_modules/hexo/lib/plugins/helper/partial.js:39:15)
    at Object.wrapper [as partial] (/workspace/blog/node_modules/lodash/lodash.js:4941:19)
    at eval (eval at compile (/workspace/blog/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:9:17)
    at returnedFn (/workspace/blog/node_modules/ejs/lib/ejs.js:580:17)
    at Theme._View.View._compiled.locals [as _compiled] (/workspace/blog/node_modules/hexo/lib/theme/view.js:124:48)
    at Theme._View.View.View.render (/workspace/blog/node_modules/hexo/lib/theme/view.js:29:15)
    at route.set (/workspace/blog/node_modules/hexo/lib/hexo/index.js:386:29)
    at tryCatcher (/workspace/blog/node_modules/bluebird/js/release/util.js:16:23)
    at /workspace/blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/workspace/blog/node_modules/hexo/lib/hexo/router.js:134:3)

**Comment by ppoffice** [comment]
@zhangws0994 https://github.com/ppoffice/hexo-theme-hueman/blob/master/_config.yml.example#L17

**Comment by bli940505** [comment]
@ppoffice what does that code snippet mean?

**Comment by ppoffice** [comment]
@bli940505 This means you forgot to set the `thumbnail` configuration in your `_config.yml` file.

**Comment by noraj** [comment]
Can we close this issue ?
