### ISSUE TITLE
themes didn't change after I cp config.yml.example to the main directory

### ISSUE THREAD

**Issue by JoJoey-X** [ppoffice/hexo-theme-hueman#259]
Theme still is Landscape, the original theme after I copied the config.yml.example from hueman directory to hexo directory.

I tried to add a themes value in the config.yml file, hueman theme was changed successfully but it didn't include css. output log was shown below:

ERROR Asset render failed: css/style.css
CoercionError: C:/Users/Joey.Chen/Hexo/JoJoeyX.github.io/themes/hueman/source/css/_variables.styl:38:54
   34| line-height-title = 1.3em
   35|
   36| // Header
   37| logo-url = hexo-config("customize.logo.url")
   38| logo-width = 0px + hexo-config("customize.logo.width")
------------------------------------------------------------^
   39| logo-height = 0px + hexo-config("customize.logo.height")
   40|
   41| // Sidebar

cannot coerce '' to unit

    at Unit.coerce (C:\Users\Joey.Chen\Hexo\JoJoeyX.github.io\node_modules\stylus\lib\nodes\node.js:250:11)
    at Unit.coerce (C:\Users\Joey.Chen\Hexo\JoJoeyX.github.io\node_modules\stylus\lib\nodes\unit.js:209:43)
    at Unit.operate (C:\Users\Joey.Chen\Hexo\JoJoeyX.github.io\node_modules\stylus\lib\nodes\unit.js:132:20)
    at Evaluator.visitBinOp (C:\Users\Joey.Chen\Hexo\JoJoeyX.github.io\node_modules\stylus\lib\visitor\evaluator.js:581:28)
    at Evaluator.Visitor.visit (C:\Users\Joey.Chen\Hexo\JoJoeyX.github.io\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (C:\Users\Joey.Chen\Hexo\JoJoeyX.github.io\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitExpression (C:\Users\Joey.Chen\Hexo\JoJoeyX.github.io\node_modules\stylus\lib\visitor\evaluator.js:644:26)
    at Evaluator.Visitor.visit (C:\Users\Joey.Chen\Hexo\JoJoeyX.github.io\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (C:\Users\Joey.Chen\Hexo\JoJoeyX.github.io\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitIdent (C:\Users\Joey.Chen\Hexo\JoJoeyX.github.io\node_modules\stylus\lib\visitor\evaluator.js:551:22)
    at Evaluator.Visitor.visit (C:\Users\Joey.Chen\Hexo\JoJoeyX.github.io\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (C:\Users\Joey.Chen\Hexo\JoJoeyX.github.io\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitBlock (C:\Users\Joey.Chen\Hexo\JoJoeyX.github.io\node_modules\stylus\lib\visitor\evaluator.js:720:39)
    at Evaluator.Visitor.visit (C:\Users\Joey.Chen\Hexo\JoJoeyX.github.io\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (C:\Users\Joey.Chen\Hexo\JoJoeyX.github.io\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.importFile (C:\Users\Joey.Chen\Hexo\JoJoeyX.github.io\node_modules\stylus\lib\visitor\evaluator.js:99:18)
    at Evaluator.visitImport (C:\Users\Joey.Chen\Hexo\JoJoeyX.github.io\node_modules\stylus\lib\visitor\evaluator.js:920:27)
    at Evaluator.Visitor.visit (C:\Users\Joey.Chen\Hexo\JoJoeyX.github.io\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (C:\Users\Joey.Chen\Hexo\JoJoeyX.github.io\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitRoot (C:\Users\Joey.Chen\Hexo\JoJoeyX.github.io\node_modules\stylus\lib\visitor\evaluator.js:707:27)
    at Evaluator.Visitor.visit (C:\Users\Joey.Chen\Hexo\JoJoeyX.github.io\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (C:\Users\Joey.Chen\Hexo\JoJoeyX.github.io\node_modules\stylus\lib\visitor\evaluator.js:160:18)

Please give some help, thank you!

**Comment by ppoffice** [comment]
@JoJoeyx Make sure you have this part.
https://github.com/ppoffice/hexo-theme-hueman/blob/master/_config.yml.example#L10-L13

**Comment by JoJoeyx** [comment]
@ppoffice thanks for the quick reply, I replace the default config.yml file with the config.yml.example included in the hueman package.

this part you shown was placed, you may check the code below:

`# Menus
menu:
    Home: /
    # Delete this row if you don't want categories in your header nav bar
    Categories:
    About: /about/index.html

# Customize
customize:
    logo:
        width: 165
        height: 60
        url: images/logo-header.png
    theme_color: '#006bde'
    highlight: androidstudio
    sidebar: left # sidebar position, options: left, right
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: # path to favicon
    social_links: # for more icons, please see http://fontawesome.io/icons/#brand
        twitter: /
        facebook: /
        google-plus: /
        github: https://github.com/ppoffice/hexo-theme-hueman
        weibo: /
        rss: /

# Widgets
widgets:
    - catalog
    - recent_posts
    - category
    - archive
    - tag
    - tagcloud
    - links

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    disqus: hexo-theme-hueman # enter disqus shortname here
    duoshuo: # enter duoshuo shortname here
    youyan: # enter youyan uid here
    facebook: # enter true to enable
    isso: # options for isso. All fields below are OPTIONAL (except for site). See https://posativ.org/isso/docs/configuration/client/ for more information.
        on: # enter true to enable isso
        site: # enter the domain name of your own comment isso server, eg. comments.example.com
        lang: # two letter language code, eg. en
        reply-to-self: # true when your server spam guard has this value set
        require-author: # true when your server spam guard has this value set
        require-email: # true when your server spam guard has this value set
        max-comments-top: # number of top level comments to show, specify "inf" for all
        max-comments-nested: # number of nested comments to show.
        reveal-on-click: # number of comments to reveal when clicking "hidden" link
        avatar: # true|false, setting to enable avatar generation
        avatar-bg: # background color of avatar, i.e. "#f0f0f0"
        avatar-fg: # set pallet of foreground colors (up to 8) i.e. "#9abf88 #5698c4 #e279a3 #9163b6"
        vote: # true|false, setting to enable voting feature on client side.
        vote-levels: # levels to customize appearance of comments, eg. "[-5, 5, 15]" or "0,5,10"
    changyan:
        appId: # enter the changyan appId here
        appKey: # enter the changyan appKey here
        on: # enter true to enable
    valine: # Valine Comment System https://github.com/xCss/Valine
        on:  # enter true to enable valine
        appId:  # enter the leancloud application appId here
        appKey:  # enter the leancloud application appKey here
        notify: # enter true to enable <Mail notifier> https://github.com/xCss/Valine/wiki/Valine-%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F%E4%B8%AD%E7%9A%84%E9%82%AE%E4%BB%B6%E6%8F%90%E9%86%92%E8%AE%BE%E7%BD%AE
        verify: # enter true to enable <Validation code>
        placeholder: Just Do It # enter the comment box placeholder
        avatar: identicon # (''/mm/identicon/monsterid/wavatar/retro/hide), more to see https://valine.js.org/avatar/
        avatar_cdn: https://gravatar.loli.net/avatar/ # avatar CDN address, default gravatar.loli.net
        pageSize: 10 # comments of one page
    gitalk:
        on: # enter true to enable gitalk
        owner: # GitHub user name
        repo: # GitHub repository name
        client_id: # OAuth application client id
        client_secret: # OAuth application client secret
        admin: # GitHub repo owner and collaborators who can initialize github issues
               # Can either be a string or an array.

# Share
share: default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    lightgallery: true # options: true, false
    justifiedgallery: true # options: true, false
    google_analytics: # enter the tracking ID for your Google Analytics
    baidu_analytics: # enter Baidu Analytics hash key
    bing_site_verification: # enter Bing verification key here
    statcounter:
      sc_project: # enter statcounter project id
      sc_invisible: # enter 1 to make statcounter invisible
      sc_security: # enter security code
      public: # enter true if you want a link to your public stats. Must be configured on statcouter as well.
      on: # enter true to enable statcounter
    mathjax: false # options: true, false

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
        Hexo: http://hexo.io

theme: hueman
`
