### ISSUE TITLE
install failed Cannot read property 'thumbnail' of undefined

### ISSUE THREAD

**Issue by gitAda16** [ppoffice/hexo-theme-hueman#266]
After i ran command "hexo g" , i got the error message like these:
C:\mysource\hexoblog\myblog\themes\hueman\layout\common\summary.ejs:3
    1| <article class="article article-summary<%= (post.direction && post.direction.toLowerCase() === 'rtl' ? ' rtl' : '') %>">
    2|     <div class="article-summary-inner">
 >> 3|         <% if (theme.customize.thumbnail === true) { %>
    4|         <%- partial('common/thumbnail', { counter: true }) %>
    5|         <% } %>
    6|         <div class="article-meta">

Cannot read property 'thumbnail' of undefined
    at eval (eval at compile (C:\mysource\hexoblog\myblog\node_modules\ejs\lib\ejs.js:633:12), <anonymous>:13:28)
    at returnedFn (C:\mysource\hexoblog\myblog\node_modules\ejs\lib\ejs.js:668:17)
    at Theme._View.View._compiledSync (C:\mysource\hexoblog\myblog\node_modules\hexo\lib\theme\view.js:119:22)
    at Theme._View.View.View.renderSync (C:\mysource\hexoblog\myblog\node_modules\hexo\lib\theme\view.js:48:23)
    at Object.partial (C:\mysource\hexoblog\myblog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (eval at compile (C:\mysource\hexoblog\myblog\node_modules\ejs\lib\ejs.js:633:12), <anonymous>:47:17)
    at _Query.forEach (C:\mysource\hexoblog\myblog\node_modules\warehouse\lib\query.js:36:7)
    at eval (eval at compile (C:\mysource\hexoblog\myblog\node_modules\ejs\lib\ejs.js:633:12), <anonymous>:12:19)
    at returnedFn (C:\mysource\hexoblog\myblog\node_modules\ejs\lib\ejs.js:668:17)
    at Theme._View.View._compiledSync (C:\mysource\hexoblog\myblog\node_modules\hexo\lib\theme\view.js:119:22)
    at Theme._View.View.View.renderSync (C:\mysource\hexoblog\myblog\node_modules\hexo\lib\theme\view.js:48:23)
    at Object.partial (C:\mysource\hexoblog\myblog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (eval at compile (C:\mysource\hexoblog\myblog\node_modules\ejs\lib\ejs.js:633:12), <anonymous>:9:17)
    at returnedFn (C:\mysource\hexoblog\myblog\node_modules\ejs\lib\ejs.js:668:17)
    at Theme._View.View._compiled (C:\mysource\hexoblog\myblog\node_modules\hexo\lib\theme\view.js:123:48)
    at Theme._View.View.View.render (C:\mysource\hexoblog\myblog\node_modules\hexo\lib\theme\view.js:29:15)
    at C:\mysource\hexoblog\myblog\node_modules\hexo\lib\hexo\index.js:365:21
    at tryCatcher (C:\mysource\hexoblog\myblog\node_modules\bluebird\js\release\util.js:16:23)
    at C:\mysource\hexoblog\myblog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (C:\mysource\hexoblog\myblog\node_modules\hexo\lib\hexo\router.js:123:3)
    at RouteStream.Readable.read (_stream_readable.js:490:10)
    at resume_ (_stream_readable.js:975:12)

What's wrong with it?

**Comment by ppoffice** [comment]
@gitAda16  Did you copy `_config.yml.example` to `_config.yml`?

**Comment by gitAda16** [comment]
@ppoffice  Thank you! I made a mistake. I copied _config.yml.example to _config.xml.
