### ISSUE TITLE
Prettier isn't working for _config.yml. Do I need to uninstall Prettier to use the theme?

### ISSUE THREAD

**Issue by heyfranksmile** [ppoffice/hexo-theme-hueman#284]
- [x] I have setuped and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [x] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-hueman/wiki) carefully and created my own configuration file(_config.yml);
- [x] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-hueman/issues) and found no duplicate issues.

Prettier isn't working for _config.yml. Do I need to uninstall Prettier to edit _config.yml or shouldn't I save the edited codes when running or deploying? 

When I try to edit something, this error message pops up. 

themes/hueman/layout/index.ejs:1
 >> 1| <%- partial('common/archive') %>

**Comment by heyfranksmile** [comment]
This is the full error I get whenever I save _config.yml file.

Theme config load failed.
ERROR Process failed: _config.yml
YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 84, column 7:
          # Can either be a string or an a ... 
          ^
    at generateError (/Users/frankkim/Desktop/strugglewithme/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
    at throwError (/Users/frankkim/Desktop/strugglewithme/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
    at readBlockMapping (/Users/frankkim/Desktop/strugglewithme/node_modules/js-yaml/lib/js-yaml/loader.js:1073:9)
    at composeNode (/Users/frankkim/Desktop/strugglewithme/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
    at readBlockMapping (/Users/frankkim/Desktop/strugglewithme/node_modules/js-yaml/lib/js-yaml/loader.js:1089:11)
    at composeNode (/Users/frankkim/Desktop/strugglewithme/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
    at readBlockMapping (/Users/frankkim/Desktop/strugglewithme/node_modules/js-yaml/lib/js-yaml/loader.js:1089:11)
    at composeNode (/Users/frankkim/Desktop/strugglewithme/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
    at readDocument (/Users/frankkim/Desktop/strugglewithme/node_modules/js-yaml/lib/js-yaml/loader.js:1525:3)
    at loadDocuments (/Users/frankkim/Desktop/strugglewithme/node_modules/js-yaml/lib/js-yaml/loader.js:1588:5)
    at Object.load (/Users/frankkim/Desktop/strugglewithme/node_modules/js-yaml/lib/js-yaml/loader.js:1614:19)
    at Hexo.yamlHelper (/Users/frankkim/Desktop/strugglewithme/node_modules/hexo/lib/plugins/renderer/yaml.js:7:15)
    at Hexo.tryCatcher (/Users/frankkim/Desktop/strugglewithme/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/frankkim/Desktop/strugglewithme/node_modules/bluebird/js/release/method.js:15:34)
    at Promise.then.text (/Users/frankkim/Desktop/strugglewithme/node_modules/hexo/lib/hexo/render.js:75:22)
    at tryCatcher (/Users/frankkim/Desktop/strugglewithme/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/frankkim/Desktop/strugglewithme/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/frankkim/Desktop/strugglewithme/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/frankkim/Desktop/strugglewithme/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/frankkim/Desktop/strugglewithme/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/frankkim/Desktop/strugglewithme/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/frankkim/Desktop/strugglewithme/node_modules/bluebird/js/release/async.js:86:9)
Unhandled rejection TypeError: /Users/frankkim/Desktop/strugglewithme/themes/hueman/layout/index.ejs:1
 >> 1| <%- partial('common/archive') %>

/Users/frankkim/Desktop/strugglewithme/themes/hueman/layout/common/archive.ejs:19
    17|         <div class="article-row">
    18|     <% } %>
 >> 19|         <%- partial('summary', { post: post }) %>
    20|     <% if (postCount == page.posts.length || postCount % 2 == 0) { %>
    21|         </div>
    22|     <% } %>

/Users/frankkim/Desktop/strugglewithme/themes/hueman/layout/common/summary.ejs:3
    1| <article class="article article-summary<%= (post.direction && post.direction.toLowerCase() === 'rtl' ? ' rtl' : '') %>">
    2|     <div class="article-summary-inner">
 >> 3|         <% if (theme.customize.thumbnail === true) { %>
    4|         <%- partial('common/thumbnail', { counter: true }) %>
    5|         <% } %>
    6|         <div class="article-meta">

Cannot read property 'thumbnail' of undefined
    at eval (/Users/frankkim/Desktop/strugglewithme/themes/hueman/layout/common/summary.ejs:14:28)
    at summary (/Users/frankkim/Desktop/strugglewithme/node_modules/ejs/lib/ejs.js:682:17)
    at viewFn._compiledSync.locals [as _compiledSync] (/Users/frankkim/Desktop/strugglewithme/node_modules/hexo/lib/theme/view.js:132:22)
    at viewFn.View.renderSync (/Users/frankkim/Desktop/strugglewithme/node_modules/hexo/lib/theme/view.js:60:23)
    at Object.partial (/Users/frankkim/Desktop/strugglewithme/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
    at eval (/Users/frankkim/Desktop/strugglewithme/themes/hueman/layout/common/archive.ejs:48:17)
    at _Query.forEach (/Users/frankkim/Desktop/strugglewithme/node_modules/warehouse/lib/query.js:36:7)
    at eval (/Users/frankkim/Desktop/strugglewithme/themes/hueman/layout/common/archive.ejs:13:19)
    at archive (/Users/frankkim/Desktop/strugglewithme/node_modules/ejs/lib/ejs.js:682:17)
    at viewFn._compiledSync.locals [as _compiledSync] (/Users/frankkim/Desktop/strugglewithme/node_modules/hexo/lib/theme/view.js:132:22)
    at viewFn.View.renderSync (/Users/frankkim/Desktop/strugglewithme/node_modules/hexo/lib/theme/view.js:60:23)
    at Object.partial (/Users/frankkim/Desktop/strugglewithme/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
    at eval (/Users/frankkim/Desktop/strugglewithme/themes/hueman/layout/index.ejs:10:17)
    at index (/Users/frankkim/Desktop/strugglewithme/node_modules/ejs/lib/ejs.js:682:17)
    at viewFn._compiled.locals [as _compiled] (/Users/frankkim/Desktop/strugglewithme/node_modules/hexo/lib/theme/view.js:136:48)
    at viewFn.View.render (/Users/frankkim/Desktop/strugglewithme/node_modules/hexo/lib/theme/view.js:41:15)
    at /Users/frankkim/Desktop/strugglewithme/node_modules/hexo/lib/hexo/index.js:61:21
    at tryCatcher (/Users/frankkim/Desktop/strugglewithme/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/frankkim/Desktop/strugglewithme/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/frankkim/Desktop/strugglewithme/node_modules/hexo/lib/hexo/router.js:126:3)
    at RouteStream.Readable.read (_stream_readable.js:470:10)
    at resume_ (_stream_readable.js:949:12)

**Comment by ppoffice** [comment]
@heyfranksmile Your `_config.yml` is malformatted. Please correct the errors in it.

```
ERROR Process failed: _config.yml
YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 84, column 7:
          # Can either be a string or an a ... 
```

**Comment by heyfranksmile** [comment]
@ppoffice  

Thanks for pointing that out. I actually tried to fix it earlier and then realized now that the code was formatting automatically so I had to move some comments.

You can close this issue.

Thank you!
