### ISSUE TITLE
hexo-theme-hueman fail to generate

### ISSUE THREAD

**Issue by drmn68** [ppoffice/hexo-theme-hueman#5]
bash$hexo clean
[info] Deleted cache file
[info] Deleted public directory
bash$git clone https://github.com/ppoffice/hexo-theme-hueman.git themes/hueman

bash$hexo g
[info] Files loaded in 0.110s
[error] HexoError: Render failed: archives/index.html
TypeError: /Users/drmn68/Development/github/hexo/themes/hueman/layout/layout.ejs:40
    38|             </div>
    39|           </section>
 >> 40|           <%- partial('_partial/sidebar') %>
    41|         </div>
    42|       </div>
    43|     </div>

/Users/drmn68/Development/github/hexo/themes/hueman/layout/_partial/sidebar.ejs:15
    13|   <% } %>
    14|   <div class="widgets-container">
 >> 15|     <% theme.widgets.forEach(function(widget){ %>
    16|       <%- partial('_widget/' + widget) %>
    17|     <% }) %>
    18|   </div>

Cannot read property 'forEach' of undefined
    at eval (eval at <anonymous> (/Users/drmn68/Development/github/hexo/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:853)
    at eval (eval at <anonymous> (/Users/drmn68/Development/github/hexo/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:1026)
    at /Users/drmn68/Development/github/hexo/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:255:15
    at Object.exports.render (/Users/drmn68/Development/github/hexo/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:293:13)
    at /Users/drmn68/Development/github/hexo/node_modules/hexo-renderer-ejs/index.js:5:14
    at Object.exports.renderSync (/usr/local/lib/node_modules/hexo/lib/core/render.js:133:12)
    at View.renderSync (/usr/local/lib/node_modules/hexo/lib/theme/view.js:183:28)
    at partial (/usr/local/lib/node_modules/hexo/lib/plugins/helper/partial.js:29:17)
    at Object.module.exports (/usr/local/lib/node_modules/hexo/lib/plugins/helper/partial.js:37:12)
    at eval (eval at <anonymous> (/Users/drmn68/Development/github/hexo/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:53:363)

**Comment by ppoffice** [comment]
You have no widgets added in _config.yml. I will fix this.

**Comment by ppoffice** [comment]
Problem solved. But I think you'd better add `widgets:` in your theme's `_config.yml` to prevent future generating failures.

**Comment by drmn68** [comment]
Thanks for the quick fix!
I pull the latest version and find it does work now.

**Comment by ppoffice** [comment]
Please close the issue.

**Comment by drmn68** [comment]
Close issue which is fixed. Good job ppoffice!
